# Generated by Django 5.1.5 on 2025-02-04 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteevent',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'event')},
        ),
    ]
